image: node:latest

before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs
  - npm i

cache:
  paths:
  - node_modules/

stages:
  - build
  # - test
  # - deploy

build:
  stage: build
  script: make build dependencies
   - npm run build
